config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "products#index"

  resource :welcome

  namespace :admin do
    resources :products
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
  end

  namespace :account do
    resources :orders
  end

  resources :products do
    member do
      post :add_to_cart
    end
  end

  resources :carts do
    member do
      delete :cart_clean
      post :order_confirm
    end
  end

  resources :cart_items

  resources :orders do
    member do
      post :alipay
      post :wechan
      post :apply_to_cancel
    end
  end

  resources :productlists

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :products, :through => :cart_items, :source => :product

  def add_product_to_cart(product)
    ci = cart_items.create
    ci.product = product
    ci.quantity = 1
    ci.save
  end

  def total_price
    sum = 0
    cart_items.each do |cart_item|
      sum += cart_item.product.price * cart_item.quantity
    end
    sum
  end

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  validates_presence_of :billing_name, :billing_address, :shipping_name, :shipping_address

  has_many :productlists

  before_create :generate_token

  belongs_to :user

  def generate_token
    self.token = SecureRandom.uuid
  end

  def pay!
    self.update(:is_paid => true)
  end

  include AASM

  aasm do
    state :order_placed, initial: true
    state :paid
    state :shipping
    state :shipped
    state :order_cancelled
    state :good_retured

    event :make_payment, after_commit: :pay! do
      transitions from: :order_placed, to: :paid
    end

    event :ship do
      transitions form: :paid, to: :shipping
    end

    event :deliver do
      transitions from: :shipping, to: :shipped
    end

    event :return_good do
      transitions form: :shipped, to: :good_retured
    end

    event :cancel_order do
      transitions form: [:order_placed, :paid], to: :order_cancelled
    end

  end


end

app/models/product.rb
class Product < ApplicationRecord

  mount_uploader :image, ImageUploader

  has_many :cart_items
  has_many :carts, :through => :cart_items, :source => :cart






end

app/models/productlist.rb
class Productlist < ApplicationRecord

  mount_uploader :image, ImageUploader

  belongs_to :order

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders

  def admin?
    is_admin
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def require_admin
    if !current_user.admin?
      redirect_to root_path
      flash[:alert] = "You are not admin"
    end
  end

  helper_method :current_cart

  def current_cart
    @current_cart ||= find_cart
  end

  protected

  def find_cart
    cart = Cart.find_by(id: session[:cart_id])
    if cart.blank?
      cart = Cart.create
    end
      session[:cart_id] = cart.id
      return cart
  end



end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :authenticate_user!

  def destroy
    @cart = current_cart
    @cart_item = @cart.cart_items.find_by(product_id: params[:id])
    @product = @cart_item.product
    @cart_item.destroy

    flash[:warning] = "你已经成功将 #{@product.title} 移出购物车"
    redirect_to :back
  end

  def update
    @cart = current_cart
    @cart_item = @cart.cart_items.find_by(product_id: params[:id])
    @product = @cart_item.product
    if @cart_item.update(cart_item_params)
      redirect_to :back
      flash[:notice] = "更改数量成功"
    else
      redirect_to :back
    end
  end

  protected

  def cart_item_params
    params.require(:cart_item).permit(:quantity)
  end


end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def index
    @cart = current_cart
  end

  def show
    @cart = current_cart
  end

  def cart_clean
    @cart = current_cart
    @cart.cart_items.destroy_all
    @cart.save
    redirect_to carts_path
    flash[:warning] = "您已经清空购物车"
  end

  def order_confirm
    @order = Order.new
    @cart = current_cart
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def show
    @order = Order.find_by(token: params[:id])
    @productlists = @order.productlists
  end

  def create
    @order = Order.new(order_params)
    @order.user = current_user
    @cart = current_cart
    @order.total = @cart.total_price
    if @order.save
      @cart.cart_items.each do |cart_item|
        @productlist = Productlist.new
        @productlist.order = @order
        @productlist.product_name = cart_item.product.title
        @productlist.product_price = cart_item.product.price
        @productlist.quantity = cart_item.quantity
        @productlist.save
      end

      OrderMailer.notify_order_placed(@order).deliver!

      flash[:notice] = "创建订单成功"
      redirect_to order_path(@order.token)
    else
      render "carts/order_confirm"
    end
  end

  def alipay
    @order = Order.find_by(token: params[:id])
    @order.make_payment!
    flash[:notice] = "该笔订单已经成功支付"
    current_cart.cart_items.destroy_all
    redirect_to :back
  end

  def wechan
    @order = Order.find_by(token: params[:id])
    @order.make_payment!
    flash[:notice] = "该笔订单已经成功支付"
    current_cart.cart_items.destroy_all
    redirect_to :back
  end

  def apply_to_cancel
    @order = Order.find_by(token: params[:id])
    OrderMailer.apply_cancel(@order).deliver!
    flash[:notice] = "已提交申请"
    redirect_to :back
  end


  protected

  def order_params
    params.require(:order).permit(:billing_name, :billing_address, :shipping_name, :shipping_address)
  end

end

app/controllers/productlists_controller.rb
class ProductlistsController < ApplicationController
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def add_to_cart
    @product = Product.find(params[:id])
    @cart_item = current_cart.cart_items.find_by(product_id: params[:id])


    if @product.quantity > 0
      if @cart_item.present?
        flash[:warning] = "购物车内已经有该商品"
        redirect_to :back
      else
        current_cart.add_product_to_cart(@product)
        flash[:notice] = "成功加入购物车"
        redirect_to :back
      end
    else
      flash[:warning] = "此商品缺少库存"
    end
  end



end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    flash[:notice] = "喵呜～"
  end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper

  def render_cart_total_price(cart)
    cart.total_price
  end

end

app/helpers/flashes_helper.rb
module FlashesHelper
  FlASH_CLASSES = { alert: "danger", notice: "success", warning: "warning" }.freeze

  def flash_class(key)
    FlASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def render_order_paid_state(order)
    if order.is_paid?
      "已付款"
    else
      "未付款"
    end
  end
end

app/helpers/productlists_helper.rb
module ProductlistsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/carts/index.html.erb
<h1>Cart</h1>

<div class="pull-right">
  <%= link_to("清空购物车", cart_clean_cart_path(current_cart), method: :delete, data: { confirm: "你确定要清空整个购物车吗？" }, :class => "btn btn-warning", :style => "margin: 0px 0px 10px 0px")%>
</div>



<table class="table table-hover">
  <tr>
    <th>Title</th>
    <th>Image</th>
    <th>Price</th>
    <th>Quantity</th>
    <th>Action</th>
  </tr>
  <% @cart.cart_items.each do |cart_item| %>
  <tr>

    <td>
      <%= link_to product_path(cart_item.product) do %>
        <%= cart_item.product.title %>
      <% end %>
    </td>
    <td>
      <%= link_to product_path(cart_item.product) do %>
        <% if cart_item.product.image.present? %>
          <%= image_tag(cart_item.product.image.thumb.url, :class => "thumbnail") %>
        <% else %>
          <%= image_tag("https://ws1.sinaimg.cn/large/006tNc79gy1fha84kunf7j305k05kaa2.jpg", :class => "thumbnail") %>
        <% end %>
      <% end %>
    </td>

    <td><%= cart_item.product.price %></td>
    <td>
      <%= form_for cart_item, url: cart_item_path(cart_item.product_id) do |f| %>
        <%= f.select :quantity, 1...cart_item.product.quantity %>
        <%= f.submit "Submit", :disable_with => "Submitting..." %>
      <% end %>
    </td>
    <td><%= link_to("删除商品", cart_item_path(cart_item.product_id), method: :delete, data: { confirm: "你确定要删除该商品吗？" }, :style => "decoration: underline;")%></td>
  </tr>

  <% end %>
</table>



<div class="pull-right cleanfix">
  总计 <%= current_cart.total_price %> RMB
</div>

<br>
<hr>

<div class="pull-right cleanfix">
  <%= link_to("确认结账", order_confirm_cart_path(current_cart), method: :post, :class => "btn btn-danger")%>
</div>

app/views/carts/order_confirm.html.erb
<h2>购物明细</h2>
<table class="table">
  <tr>
    <th>Product Title</th>
    <th>Product Image</th>
    <th>Product Price</th>
    <th>Product Quantity</th>
  </tr>
  <% @cart.cart_items.each do |cart_item| %>
  <tr>
    <td>
      <%= link_to product_path(cart_item.product) do %>
        <%= cart_item.product.title %>
      <% end %>
    </td>
    <td>
      <%= link_to product_path(cart_item.product) do %>
        <% if cart_item.product.image.present? %>
          <%= image_tag(cart_item.product.image.thumb.url, :class => "thumbnail") %>
        <% else %>
          <%= image_tag("https://ws1.sinaimg.cn/large/006tNc79gy1fha84kunf7j305k05kaa2.jpg", :class => "thumbnail") %>
        <% end %>
      <% end %>
    </td>
    <td><%= cart_item.product.price %></td>
    <td><%= cart_item.quantity %></td>
  </tr>
  <% end %>
</table>

<div class="pull-right cleanfix">
  总计 <%= current_cart.total_price %> RMB
</div>

<br>
<hr>

<h2>订单资讯</h2>


<%= simple_form_for @order do |f| %>
  <legend>订购人</legend>
  <%= f.input :billing_name %>
  <%= f.input :billing_address %>
  <legend>收货人</legend>
  <%= f.input :shipping_name %>
  <%= f.input :shipping_address %>
  <%= f.submit "生成订单", :class => "btn btn-danger pull-right" , :disable_with => "Submitting..." %>
<% end %>

app/views/carts/show.html.erb
<h1>Cart</h1>

<table class="table table-hover">
  <tr>
    <th>#</th>
    <th>Image</th>
    <th>Title</th>
    <th>Price</th>
    <th>Quantity</th>
  </tr>
  <% @cart.cart_items.each do |cart_item| %>
  <tr>
    <td><%= cart_item.id %></td>
    <td><%= image_tag(cart_item.product.image.thumb.url, :class => "thumbnail") %></td>
    <td><%= cart_item.product.title %></td>
    <td><%= cart_item.product.price %></td>
    <td><%= cart_item.quantity %></td>
  </tr>
  <% end %>

</table>

<div class="pull-right">
  总计 <%= render_cart_total_price(current_cart) %> RMB
</div>