config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "products#index"

  resource :welcome

  namespace :admin do
    resources :products
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
  end

  namespace :account do
    resources :orders
  end

  resources :products do
    member do
      post :add_to_cart
    end
  end

  resources :carts do
    member do
      delete :cart_clean
      post :order_confirm
    end
  end

  resources :cart_items

  resources :orders do
    member do
      post :alipay
      post :wechan
      post :apply_to_cancel
    end
  end

  resources :productlists

end

app/models/product.rb
class Product < ApplicationRecord

  mount_uploader :image, ImageUploader

  has_many :cart_items
  has_many :carts, :through => :cart_items, :source => :cart






end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_admin
  layout "admin"

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Product created"
      redirect_to admin_products_path
    else
      render "new"
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = "Update success"
      redirect_to admin_products_path
    else
      render "edit"
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to admin_products_path
  end

  protected

  def product_params
    params.require(:product).permit(:title, :description, :price, :quantity, :image)
  end

  def require_admin
    if !current_user.admin?
      redirect_to root_path
      flash[:alert] = "You are not admin"
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def add_to_cart
    @product = Product.find(params[:id])
    @cart_item = current_cart.cart_items.find_by(product_id: params[:id])


    if @product.quantity > 0
      if @cart_item.present?
        flash[:warning] = "购物车内已经有该商品"
        redirect_to :back
      else
        current_cart.add_product_to_cart(@product)
        flash[:notice] = "成功加入购物车"
        redirect_to :back
      end
    else
      flash[:warning] = "此商品缺少库存"
    end
  end



end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= simple_form_for [:admin, @product] do |p| %>
  <%= p.input :title %>
  <%= p.input :description %>
  <%= p.input :price %>
  <%= p.input :quantity %>
  <%= p.input :image %>
  <%= p.submit "Submit", :disable_with => "Submitting..."%>
<% end %>

app/views/admin/products/edit.html.erb
<h1>Edit Product</h1>

<%= render "form" %>

app/views/admin/products/index.html.erb
<h1>Product List</h1>
<div class="pull-right">
  <%= link_to("Add new product", new_admin_product_path, :class => "btn btn-primary", :style => "margin: 0px 0px 10px;")%>
</div>

<table class="table table-board">
  <tr>
    <th>#</th>
    <th>Image</th>
    <th>Title</th>
    <th>Price</th>
    <th>Action</th>
  </tr>
  <% @products.each do |product| %>
  <tr>
    <td><%= product.id %></td>
    <td>
      <% if product.image.present? %>
        <%= image_tag(product.image.thumb.url)%>
      <% else %>
        <%= image_tag("https://ws1.sinaimg.cn/large/006tNc79gy1fha84kunf7j305k05kaa2.jpg", class: "thumbnail")%>
      <% end %>

    </td>
    <td><%= product.title %></td>
    <td>¥<%= product.price %></td>
    <td>
      <%= link_to("Edit", edit_admin_product_path(product), :class => "btn btn-default") %> |
      <%= link_to("Delete", admin_product_path(product), :class => "btn btn-default", method: :delete) %>
    </td>
  </tr>
  <% end %>
</table>

app/views/admin/products/new.html.erb
<h1>New Product</h1>

<%= render "form" %>

app/views/admin/products/show.html.erb
<h1>Admin::Products#show</h1>
<p>Find me in app/views/admin/products/show.html.erb</p>