config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "products#index"

  resource :welcome

  namespace :admin do
    resources :products
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
  end

  namespace :account do
    resources :orders
  end

  resources :products do
    member do
      post :add_to_cart
    end
  end

  resources :carts do
    member do
      delete :cart_clean
      post :order_confirm
    end
  end

  resources :cart_items

  resources :orders do
    member do
      post :alipay
      post :wechan
      post :apply_to_cancel
    end
  end

  resources :productlists

end

app/models/product.rb
class Product < ApplicationRecord

  mount_uploader :image, ImageUploader

  has_many :cart_items
  has_many :carts, :through => :cart_items, :source => :cart






end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_admin
  layout "admin"

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Product created"
      redirect_to admin_products_path
    else
      render "new"
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = "Update success"
      redirect_to admin_products_path
    else
      render "edit"
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to admin_products_path
  end

  protected

  def product_params
    params.require(:product).permit(:title, :description, :price, :quantity, :image)
  end

  def require_admin
    if !current_user.admin?
      redirect_to root_path
      flash[:alert] = "You are not admin"
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def add_to_cart
    @product = Product.find(params[:id])
    @cart_item = current_cart.cart_items.find_by(product_id: params[:id])


    if @product.quantity > 0
      if @cart_item.present?
        flash[:warning] = "购物车内已经有该商品"
        redirect_to :back
      else
        current_cart.add_product_to_cart(@product)
        flash[:notice] = "成功加入购物车"
        redirect_to :back
      end
    else
      flash[:warning] = "此商品缺少库存"
    end
  end



end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/index.html.erb
<h1>Products</h1>

<% @products.each do |p| %>
  <div class="col-md-3 product">
    <p>
      <a href="<%= product_path(p) %>">
        <% if p.image.present? %>
          <%= image_tag(p.image.medium.url, :class => "thumbnail")%>
        <% else %>
          <%= image_tag("https://ws3.sinaimg.cn/large/006tNbRwgy1fh9u5gz7lkj30b30b4mxh.jpg", class: "thumbnail")%>
        <% end %>
      </a>
    </p>
    <p><%= link_to p.title, product_path(p) %></p>
    <p>Price: ¥<%= p.price %></p>
    <p>Quantity: <%= p.quantity %></p>
    <p>
      <div class="pull-right clearfix">
        <% if p.quantity > 0 %>
          <%= link_to("加入购物车", add_to_cart_product_path(p), :method => :post, :class => "btn btn-danger") %>
        <% else %>
          商品已售空
        <% end %>
      </div>
    </p>

  </div>
<% end %>

app/views/products/show.html.erb
<div class="row">
  <div class="col-md-6">
    <% if @product.image.present? %>
      <%= image_tag(@product.image.url, class: "thumbnail")%>
    <% else %>
      <%= image_tag("https://ws3.sinaimg.cn/large/006tNbRwgy1fh9u5gz7lkj30b30b4mxh.jpg", class: "thumbnail")%>
    <% end %>
  </div>

  <div class="col-md-6">
    <h2><%= @product.title %></h2>
    <div>
      <p>Description:<%= @product.description %></p>
    </div>
    <p>Price: ¥<%= @product.price %></p>
    <p>Quantity: <%= @product.quantity %></p>

    <div class="pull-right clearfix">
      <% if @product.quantity > 0 %>
        <%= link_to("加入购物车", add_to_cart_product_path(@product), :method => :post, :class => "btn btn-lg btn-danger") %>
      <% else %>
        商品已售空
      <% end %>
    </div>

  </div>


</div>